name: Build and Release DLL

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MinGW-w64
        run: choco install mingw -y
      - name: Build DLL
        run: |
          g++ -shared -static-libgcc -static-libstdc++ -static -O2 -o dinput8.dll AutoClickProxy.cpp -lgdi32
      - uses: actions/upload-artifact@v4
        with:
          name: autoclick-artifacts
          path: |
            dinput8.dll
            config.ini
  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: autoclick-artifacts
          path: ./release
      - name: List release files
        run: dir ./release
      - name: Set ZIP name with version
        id: zipname
        run: |
          $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
          echo "ZIP_NAME=autoclick-$tag.zip" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Create ZIP package
        run: |
          powershell Compress-Archive -Path ./release/dinput8.dll, ./release/config.ini -DestinationPath ./$env:ZIP_NAME
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ github.token }}
